# Autogenerated wrapper script for opencl_kernel_profiler_jll for aarch64-apple-darwin
export libopencl_kernel_profiler

using OpenCL_jll
using perfetto_jll
using SPIRV_Tools_jll
JLLWrappers.@generate_wrapper_header("opencl_kernel_profiler")
JLLWrappers.@declare_library_product(libopencl_kernel_profiler, "@rpath/libopencl-kernel-profiler.dylib")
function __init__()
    JLLWrappers.@generate_init_header(OpenCL_jll, perfetto_jll, SPIRV_Tools_jll)
    JLLWrappers.@init_library_product(
        libopencl_kernel_profiler,
        "lib/libopencl-kernel-profiler.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
