# Autogenerated wrapper script for opencl_kernel_profiler_jll for x86_64-w64-mingw32-cxx11
export libopencl_kernel_profiler

using OpenCL_jll
using perfetto_jll
using SPIRV_Tools_jll
JLLWrappers.@generate_wrapper_header("opencl_kernel_profiler")
JLLWrappers.@declare_library_product(libopencl_kernel_profiler, "libopencl-kernel-profiler.dll")
function __init__()
    JLLWrappers.@generate_init_header(OpenCL_jll, perfetto_jll, SPIRV_Tools_jll)
    JLLWrappers.@init_library_product(
        libopencl_kernel_profiler,
        "bin\\libopencl-kernel-profiler.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
